#!/bin/bash
echo "Starting POX controller first, then run topology files manually"
echo "Test commands to run inside mininet> prompt:"
echo ""
echo "=== Topology A ==="
echo "  pingall"
echo "  h1 ping -c 5 h3     # same switch, expect ~10ms"
echo "  h1 ping -c 5 h2     # cross switch, expect ~50ms"
echo "  h3 iperf -s &"
echo "  h1 iperf -c 10.0.0.3 -t 10   # expect ~90 Mbps"
echo "  h2 iperf -s &"
echo "  h1 iperf -c 10.0.0.2 -t 10   # expect ~10 Mbps"
echo ""
echo "=== Topology B ==="
echo "  pingall"
echo "  h1 ping -c 5 h2"
echo "  h2 iperf -s &"
echo "  h1 iperf -c 10.0.0.2 -t 10   # expect ~50 Mbps"
